### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by MGatner** [leppert/WordPress-OCR-Plugin#1]
Hi! I’m interested in resurrecting this project. Do you have any interest in maintaining it again, or should I fork and move on? You have no additional license file - do you have any restrictions on top of the WordPress Plugins restrictions?

**Comment by leppert** [comment]
Added an MIT license. I won’t be maintaining it so you should feel free to fork and direct people to your version.

**Comment by MGatner** [comment]
Thanks so much! How about the WordPress plugin? Would you prefer I create a new one and let "OCR" be?

**Comment by leppert** [comment]
If I can find a way to add you as an admin on that, I’m happy to do it. I’ll take a look some time next week. If you already know how, feel free to post instructions here.

**Comment by leppert** [comment]
On second thought, I think it’s best to create an entirely new plugin.
